### ISSUE TITLE
Informação Ambígua no fluxo principal de solicitar troco

### ISSUE THREAD

**Issue by LucasAlmeida04** [patrickm97/Source-Code-Inspection#11]
No ponto 3 do fluxo principal, não se explicita que o saldo que é zerado é o do usuário e não do da máquina

![image](https://github.com/patrickm97/Source-Code-Inspection/assets/100705918/b16502b5-9d1b-459c-b04c-350d885030a8)

**Comment by LucasAlmeida04** [comment]
Trecho que foi corrigido na wiki:

https://github.com/patrickm97/Source-Code-Inspection/wiki/Informa%C3%A7%C3%A3o-Amb%C3%ADgua-no-fluxo-principal-de-solicitar-troco

**Comment by patrickm97** [comment]
Documentação da correção da issue na Wiki:
https://github.com/patrickm97/Source-Code-Inspection/wiki
