### ISSUE TITLE
Falta de Fluxo de Exceção

### ISSUE THREAD

**Issue by LucasAlmeida04** [patrickm97/Source-Code-Inspection#7]
Na parte de solicitar troco, o correto era ter um fluxo de exceção para caso o usuário não tenha saldo em conta ao solicitar troco

![image](https://github.com/patrickm97/Source-Code-Inspection/assets/100705918/6d4aa942-60b9-4025-a783-f59ec9f4dd7d)

**Comment by LucasAlmeida04** [comment]
Trecho corrigido na wiki:

https://github.com/patrickm97/Source-Code-Inspection/wiki/Falta-de-Fluxo-de-Exce%C3%A7%C3%A3o

**Comment by LucasAlmeida04** [comment]
Trecho corrigido na wiki:

https://github.com/patrickm97/Source-Code-Inspection/wiki/Falta-de-Fluxo-de-Exce%C3%A7%C3%A3o

**Comment by patrickm97** [comment]
Correção da issue documentada na Wiki:
https://github.com/patrickm97/Source-Code-Inspection/wiki
