### ISSUE TITLE
Falta de pré-condição em Solicitar bilhete

### ISSUE THREAD

**Issue by LucasAlmeida04** [patrickm97/Source-Code-Inspection#9]
Neste caso, deveria ter uma pré-condição para solicitar bilhete, informando que o usuário, necessariamente, precisa ter saldo para poder fazer a solicitação

![image](https://github.com/patrickm97/Source-Code-Inspection/assets/100705918/d5f8c216-a840-4f05-9557-f1201a09c56d)

**Comment by LucasAlmeida04** [comment]
Trecho corrigido na wiki:

https://github.com/patrickm97/Source-Code-Inspection/wiki/Falta-de-pr%C3%A9%E2%80%90condi%C3%A7%C3%A3o-em-Solicitar-bilhete

**Comment by patrickm97** [comment]
Correção da issue documentada na Wiki:
https://github.com/patrickm97/Source-Code-Inspection/wiki
